### here we test without an parameter (should return error)
POST http://localhost:5000/tasks
Content-Type:  application/json

{
  "task_name": "this is a test name",
  "user_id": "4321",
  "created_at": "2025-10-01 11:57:39.947488+02:00",
  "status": "completed",
  "due_date": "2025-10-02"
}
